### ISSUE TITLE
Tag people with @

### ISSUE THREAD

**Issue by synox** [adobe/franklin-chat-ui#27] opened 2023-07-10 16:47 UTC
### Expected Behaviour
@acapt should be transformed to a user reference in Slack. 

### Actual Behaviour
@acapt is rendered as plain text in Slack. 

#### Steps to Reproduce
type @acapt in the chat UI

**Comment by rofe** [comment] 2023-07-24 13:23
Duplicate of #11

**Closed as completed by rofe** 2023-07-24 13:23 UTC
Labels: duplicate
